### ISSUE TITLE
Export IL

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-infrastructure-list#9]
- Add filters 
- Add view of what will be exported

**Comment by PierreAnctil** [comment]
closely related to #8

**Comment by WorldSkillsFrance** [comment]
Hi @fabian @gbervik ,

there is also a bud when we extract data from a skill : (requested items for skill)
files are not on the good colom
![image](https://user-images.githubusercontent.com/33081412/39423363-e0046d4c-4c71-11e8-91f0-c64754ec3a8d.png)
Could you have a look to fix that please ? (I did check in other extraction)

**Comment by PierreAnctil** [comment]
@WorldSkillsFrance I added the computation on quantity (code review pending)

**Comment by fabian** [comment]
@WorldSkillsFrance  Okay, I've merged the calculated quantity and added the missing unit column header. Deployed to production.

**Comment by WorldSkillsFrance** [comment]
@fabian there is still some bug in extraction i guess all colonne are in the right place as you can see below : 
![image](https://user-images.githubusercontent.com/33081412/39568854-dab4b35c-4ec3-11e8-8122-dfe03d01007d.png)
data in "PO number" in colonne AC should be in the colonne AD also the same with AI

**Comment by fabian** [comment]
@WorldSkillsFrance Ah yes, that's a bug, thanks! Fixed now on staging. Will deploy to production on Monday.

**Comment by WorldSkillsFrance** [comment]
Hi @PierreAnctil 
Please find below a video (who start at 20sec) about several bug of extraction. Could you have look/answer/fix all bug.
https://www.dropbox.com/s/ynb0j6cc8u3aoju/Bug%20extraction.mp4?dl=0
Waiting for you retourn

**Comment by PierreAnctil** [comment]
As discussed the description issue is addressed in #89 

Factor is 

![image](https://user-images.githubusercontent.com/6544411/40428702-27267eb8-5ea1-11e8-9e83-c6c5ec5f4aad.png)

Part number is

![image](https://user-images.githubusercontent.com/6544411/40428730-3c1ab776-5ea1-11e8-8fd9-20e640e75fb5.png)

I submitted a fix for the supplier which was the supplied item supplier. Now it will be the requested item potential supplier. (https://github.com/worldskills/API-Infrastructure-List/pull/33)

I also submitted a fix for the energy. Note that after consulting @fabian I harmonized the meaning of energy with the rest of the application and now air and electricity are considered energy but not water. (https://github.com/worldskills/API-Infrastructure-List/pull/33)

I checked with a fully inputed item and all the columns are filled correctly.

**Comment by ailtisWSFR** [comment]
@PierreAnctil Thanks for those explanations. 
I do understand the issue #89 explaining the empty column for "Description".

From the video, 2 bugs remain: 
1 - I understand now the "Factor" column, but the traduction should be "Multiplicateur" instead of "Facteur" to be understood correctly and match the traduction of the tool "Add item". Thanks in advance to change that. 
2 -  The column "Energy" has disappeared from the export now. I understand and agree with @fabian  about the harmonization of the meaning "energy". But at least we need the information about the "Electricity" to appears as well, the same as the column "Air" with the "N" or "Y". 
Could you please have a look at that and add the "Electricity" column on the export? 

Thanks

**Comment by fabian** [comment]
@ailtisWSFR I have just deployed some fixes from @PierreAnctil to production. Please check again if the export still has issues.

**Comment by ailtisWSFR** [comment]
@fabian @PierreAnctil The export still has issues :  **Still no "Electricity" column**

@PierreAnctil you can forget the change about "Facteur", I've realized that another column already has the name "Multiplicateur". Sorry for that.

**Comment by PierreAnctil** [comment]
@ailtisWSFR I've just made an export in production and the columns energy and electricity are here: 
![image](https://user-images.githubusercontent.com/6544411/40660985-e17c7fdc-6352-11e8-9a4c-bf7973d40f11.png)

Maybe you are not talking about the export described in this issue (export in the requested items search page) but rather about the global export on the main page?

**Comment by ailtisWSFR** [comment]
@PierreAnctil Yes, sorry, I'm talking about the global export. I thought that this issue was about all the IL's export. Still, the bug remains and need to be fixed.

**Comment by PierreAnctil** [comment]
@ailtisWSFR Well it's not exactly a bug since no one ever expressed the need to have this column here. It has also nothing to do with Axiocode developments so I suppose @worldskills/geeks should take care of it. Finally this should be put in a separate issue since it is not related to the new export described here.

**Comment by fabian** [comment]
@ailtisWSFR I've added Energy and Electricity to the "global exports".

**Comment by fabian** [comment]
@ailtisWSFR Can we close this issue?

**Comment by ailtisWSFR** [comment]
@fabian Yes, we can. Thanks.
